Raise minimum rust version to 1.34
Required by use of TryFrom in our byteorder dependency.

    error[E0658]: use of unstable library feature 'try_from' (see issue #33417)
      --> byteorder-1.4.3/src/lib.rs:74:5
       |
    74 |     convert::TryInto, fmt::Debug, hash::Hash, ptr::copy_nonoverlapping, slice,
       |     ^^^^^^^^^^^^^^^^

    error[E0658]: use of unstable library feature 'try_from' (see issue #33417)
        --> byteorder-1.4.3/src/lib.rs:1973:37
         |
    1973 |         u16::from_be_bytes(buf[..2].try_into().unwrap())
         |                                     ^^^^^^^^

    error[E0658]: use of unstable library feature 'try_from' (see issue #33417)
        --> byteorder-1.4.3/src/lib.rs:1978:37
         |
    1978 |         u32::from_be_bytes(buf[..4].try_into().unwrap())
         |                                     ^^^^^^^^

    error[E0658]: use of unstable library feature 'try_from' (see issue #33417)
        --> byteorder-1.4.3/src/lib.rs:1983:37
         |
    1983 |         u64::from_be_bytes(buf[..8].try_into().unwrap())
         |                                     ^^^^^^^^

    error[E0658]: use of unstable library feature 'try_from' (see issue #33417)
        --> byteorder-1.4.3/src/lib.rs:1988:39
         |
    1988 |         u128::from_be_bytes(buf[..16].try_into().unwrap())
         |                                       ^^^^^^^^

    error[E0658]: use of unstable library feature 'try_from' (see issue #33417)
        --> byteorder-1.4.3/src/lib.rs:2189:37
         |
    2189 |         u16::from_le_bytes(buf[..2].try_into().unwrap())
         |                                     ^^^^^^^^

    error[E0658]: use of unstable library feature 'try_from' (see issue #33417)
        --> byteorder-1.4.3/src/lib.rs:2194:37
         |
    2194 |         u32::from_le_bytes(buf[..4].try_into().unwrap())
         |                                     ^^^^^^^^

    error[E0658]: use of unstable library feature 'try_from' (see issue #33417)
        --> byteorder-1.4.3/src/lib.rs:2199:37
         |
    2199 |         u64::from_le_bytes(buf[..8].try_into().unwrap())
         |                                     ^^^^^^^^

    error[E0658]: use of unstable library feature 'try_from' (see issue #33417)
        --> byteorder-1.4.3/src/lib.rs:2204:39
         |
    2204 |         u128::from_le_bytes(buf[..16].try_into().unwrap())
         |                                       ^^^^^^^^