Raise minimum tested compiler to 1.60
Required by byteorder dependency:

    error: package `byteorder v1.5.0` cannot be built because it
    requires rustc 1.60 or newer, while the currently active rustc
    version is 1.56.1